version: "3"

services:
  db:
    image: postgres:15
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER=su
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=tutor
  web:
    build:
      context: .
    env_file:
      - .env.master
    volumes:
      - .:/app
    ports:
      - "${PORT}:8000"
    depends_on:
      - db
