"""Category

Revision ID: 6865db73ec34
Revises: 868f1fbadc41
Create Date: 2023-04-12 07:44:17.354750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6865db73ec34'
down_revision = '868f1fbadc41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('category_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_names_id'), 'category_names', ['id'], unique=False)
    op.drop_index('ix_texts_id', table_name='texts')
    op.drop_table('texts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name='texts_language_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='texts_pkey')
    )
    op.create_index('ix_texts_id', 'texts', ['id'], unique=False)
    op.drop_index(op.f('ix_category_names_id'), table_name='category_names')
    op.drop_table('category_names')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
